In [20]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import json
import scipy.stats as st
from scipy.stats import linregress
import datetime
from datetime import datetime, timedelta
from datetime import timezeone

ImportError: cannot import name 'timezeone' from 'datetime' (/opt/anaconda3/envs/PythonData/lib/python3.8/datetime.py)

In [3]:
### Import Sector Data

SP500_Material= pd.read_csv("Resources/Sectors/XLB.csv")
SP500_Energy= pd.read_csv("Resources/Sectors/XLE.csv")
SP500_Finance= pd.read_csv("Resources/Sectors/XLF.csv")
SP500_Industrial= pd.read_csv("Resources/Sectors/XLI.csv")
SP500_Tech= pd.read_csv("Resources/Sectors/XLK.csv")
SP500_Staples= pd.read_csv("Resources/Sectors/XLP.csv")
SP500_Utilities= pd.read_csv("Resources/Sectors/XLU.csv")
SP500_Health= pd.read_csv("Resources/Sectors/XLV.csv")
SP500_Discretionary= pd.read_csv("Resources/Sectors/XLY.csv")

In [4]:
### Sector Data
SP500_Material= SP500_Material.drop(columns=['High','Low', 'Adj Close'])
SP500_Material= SP500_Material.rename(columns={'Open': 'SPMAT_Open',
                        'Close':'SPMAT_Close',
                        'Volume':'SPMAT_Volume'})

##Energy
SP500_Energy= SP500_Energy.drop(columns=['High','Low', 'Adj Close'])
SP500_Energy= SP500_Energy.rename(columns={'Open': 'SPENERGY_Open',
                        'Close':'SPENERGY_Close',
                        'Volume':'SPENERGY_Volume'})
##Finance
SP500_Finance= SP500_Finance.drop(columns=['High','Low', 'Adj Close'])
SP500_Finance= SP500_Finance.rename(columns={'Open': 'SPFINANCE_Open',
                        'Close':'SPFINANCE_Close',
                        'Volume':'SPFINANCE_Volume'})

## Industrial

SP500_Industrial=SP500_Industrial.drop(columns=['High','Low', 'Adj Close'])
SP500_Industrial= SP500_Industrial.rename(columns={'Open': 'SPINDUS_Open',
                        'Close':'SPINDUS_Close',
                        'Volume':'SPINDUS_Volume'})
##Tech
SP500_Tech=SP500_Tech.drop(columns=['High','Low', 'Adj Close'])
SP500_Tech= SP500_Tech.rename(columns={'Open': 'SPTech_Open',
                        'Close':'SPTech_Close',
                        'Volume':'SPTech_Volume'})

##Staples
SP500_Staples=SP500_Staples.drop(columns=['High','Low', 'Adj Close'])
SP500_Staples= SP500_Staples.rename(columns={'Open': 'SPStaples_Open',
                        'Close':'SPStaples_Close',
                        'Volume':'SPStaples_Volume'})

#Utilities
SP500_Utilities=SP500_Utilities.drop(columns=['High','Low', 'Adj Close'])
SP500_Utilities= SP500_Utilities.rename(columns={'Open': 'SPUTIL_Open',
                        'Close':'SPUTIL_Close',
                        'Volume':'SPUTIL_Volume'})

##Health
SP500_Health=SP500_Health.drop(columns=['High','Low', 'Adj Close'])
SP500_Health= SP500_Health.rename(columns={'Open': 'SPHealth_Open',
                        'Close':'SPHealth_Close',
                        'Volume':'SPHealth_Volume'})
SP500_Health

##Discretionary
SP500_Discretionary =SP500_Discretionary.drop(columns=['High','Low', 'Adj Close'])
SP500_Discretionary= SP500_Discretionary.rename(columns={'Open': 'SPDisc_Open',
                        'Close':'SPDisc_Close',
                        'Volume':'SPDisc_Volume'})

In [5]:
### Create combined SP500 
Combined_SP500= SP500_Material.merge(SP500_Energy, how='left')
Combined_SP500= Combined_SP500.merge(SP500_Finance, how='left')
Combined_SP500= Combined_SP500.merge(SP500_Industrial, how='left')
Combined_SP500= Combined_SP500.merge(SP500_Tech, how='left')
Combined_SP500= Combined_SP500.merge(SP500_Staples, how='left')
Combined_SP500= Combined_SP500.merge(SP500_Utilities, how='left')
Combined_SP500= Combined_SP500.merge(SP500_Health, how='left')
Combined_SP500= Combined_SP500.merge(SP500_Discretionary, how='left')

Combined_SP500

,Date,SPMAT_Open,SPMAT_Close,SPMAT_Volume,SPENERGY_Open,SPENERGY_Close,SPENERGY_Volume,SPFINANCE_Open,SPFINANCE_Close,SPFINANCE_Volume,...,SPStaples_Volume,SPUTIL_Open,SPUTIL_Close,SPUTIL_Volume,SPHealth_Open,SPHealth_Close,SPHealth_Volume,SPDisc_Open,SPDisc_Close,SPDisc_Volume
0,1998-12-22,20.781250,20.828125,1900,23.312500,23.265625,15200,19.052092,18.937855,55887,...,150300,30.250000,29.828125,7900,24.812500,25.031250,5700,25.312500,25.468750,3700
1,1998-12-23,20.968750,21.046875,700,23.343750,23.750000,67800,18.861698,19.217100,78784,...,44000,29.796875,29.703125,24100,25.187500,25.593750,18100,25.500000,25.578125,12000
2,1998-12-24,21.296875,21.531250,1500,23.812500,23.625000,12300,19.217100,19.344028,43824,...,45500,30.218750,30.250000,23800,25.625000,25.750000,4900,25.937500,26.046875,1600
3,1998-12-28,21.500000,21.343750,2500,23.750000,23.500000,13500,19.331335,19.090172,51948,...,25400,30.187500,30.093750,3100,25.671875,25.375000,15500,25.921875,25.812500,8600
4,1998-12-29,21.734375,21.734375,100,23.562500,23.734375,22000,19.115557,19.293259,100819,...,123500,30.218750,30.593750,12000,25.375000,25.937500,5300,25.890625,26.375000,1100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5828,2022-02-18,84.180000,83.860001,8964800,67.500000,68.050003,31630200,39.189999,39.220001,47813800,...,16469700,66.120003,66.220001,16843400,128.350006,127.510002,13505000,181.600006,180.000000,9495200
5829,2022-02-22,83.459999,82.669998,10654400,70.110001,66.949997,46501400,39.040001,39.020000,60719700,...,21545800,66.459999,66.150002,17210700,127.059998,127.190002,13682100,177.479996,174.750000,13672800
5830,2022-02-23,83.199997,81.610001,9581100,67.339996,67.639999,33979000,39.310001,38.340000,64169800,...,15134300,66.269997,65.029999,17291800,127.839996,126.550003,12022800,176.119995,168.910004,13567200
5831,2022-02-24,79.769997,81.370003,15903500,69.080002,67.110001,61742900,37.070000,37.880001,143075700,...,30125500,64.610001,65.550003,28660000,124.290001,127.059998,23220000,161.970001,172.770004,20868000
5832,2022-02-25,81.739998,84.339996,11129200,67.260002,68.879997,39203200,38.130001,39.099998,99105200,...,21138400,66.129997,67.580002,21264000,127.629997,130.949997,17010500,173.289993,176.190002,13669000

In [6]:
### Import the data 

VIX = pd.read_csv("Resources/^VIX.csv")
DOWJONES = pd.read_csv("Resources/DIA.csv")
GLD = pd.read_csv("Resources/GLD.csv")
RUSSELL2K = pd.read_csv("Resources/IWM.csv")
NASDAQ = pd.read_csv("Resources/QQQ.csv")
TENYEAR= pd.read_csv("Resources/^TNX.csv")
SPY=pd.read_csv("Resources/SPY.csv")

####Drop columns and update data
## VIX
VIX= VIX.drop(columns=['High','Low', 'Adj Close'])
VIX= VIX.rename(columns={'Open': 'VIX_Open',
                        'Close':'VIX_Close',
                        'Volume':'VIX_Volume'})
## DOW
DOWJONES= DOWJONES.drop(columns=['High','Low', 'Adj Close'])
DOWJONES= DOWJONES.rename(columns={'Open': 'DOW_Open',
                        'Close':'DOW_Close',
                        'Volume':'DOW_Volume'})
## GLD
GLD= GLD.drop(columns=['High','Low', 'Adj Close'])
GLD= GLD.rename(columns={'Open': 'GLD_Open',
                        'Close':'GLD_Close',
                        'Volume':'GLD_Volume'})
## Russell 2k
RUSSELL2K= RUSSELL2K.drop(columns=['High','Low', 'Adj Close'])
RUSSELL2K= RUSSELL2K.rename(columns={'Open': 'R2K_Open',
                        'Close':'R2K_Close',
                        'Volume':'R2K_Volume'})

## NASDAQ
NASDAQ= NASDAQ.drop(columns=['High','Low', 'Adj Close'])
NASDAQ= NASDAQ.rename(columns={'Open': 'NASDAQ_Open',
                        'Close':'NASDAQ_Close',
                        'Volume':'NASDAQ_Volume'})
## 10YR
TENYEAR= TENYEAR.drop(columns=['High','Low', 'Adj Close'])
TENYEAR= TENYEAR.rename(columns={'Open': '10YR_Open',
                        'Close':'10YR_Close',
                        'Volume':'10YR_Volume'})

## SPY

SPY= SPY.drop(columns=['High','Low', 'Adj Close'])
SPY= SPY.rename(columns={'Open': 'SPY_Open',
                        'Close':'SPY_Close',
                        'Volume':'SPY_Volume'})

In [7]:
### Create Combined DF VIX  DOWJONES GLD RUSSELL2K NASQAD  TENYEAR SPY

Combined_Variables=VIX.merge(DOWJONES, how='left')
Combined_Variables= Combined_Variables.merge(GLD, how='left')
Combined_Variables= Combined_Variables.merge(RUSSELL2K, how='left')
Combined_Variables= Combined_Variables.merge(NASDAQ, how='left')
Combined_Variables= Combined_Variables.merge(TENYEAR, how='left')
Combined_Variables= Combined_Variables.merge(SPY, how='left')
Combined_Variables

,Date,VIX_Open,VIX_Close,VIX_Volume,DOW_Open,DOW_Close,DOW_Volume,GLD_Open,GLD_Close,GLD_Volume,...,R2K_Volume,NASDAQ_Open,NASDAQ_Close,NASDAQ_Volume,10YR_Open,10YR_Close,10YR_Volume,SPY_Open,SPY_Close,SPY_Volume
0,1990-01-02,17.240000,17.240000,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.940,7.940,0.0,NaN,NaN,NaN
1,1990-01-03,18.190001,18.190001,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.990,7.990,0.0,NaN,NaN,NaN
2,1990-01-04,19.219999,19.219999,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.980,7.980,0.0,NaN,NaN,NaN
3,1990-01-05,20.110001,20.110001,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.990,7.990,0.0,NaN,NaN,NaN
4,1990-01-08,20.260000,20.260000,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.020,8.020,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8097,2022-02-18,26.660000,27.750000,0,342.899994,340.980011,6191000.0,177.070007,177.119995,12754400.0,...,36203900.0,346.410004,341.510010,79821000.0,1.960,1.932,0.0,437.329987,434.230011,132642900.0
8098,2022-02-22,31.799999,28.809999,0,338.790009,336.010010,7942700.0,177.669998,177.490005,14960500.0,...,31847100.0,338.489990,338.079987,85967100.0,1.944,1.948,0.0,431.890015,429.570007,124391800.0
8099,2022-02-23,28.040001,31.020000,0,338.160004,331.519989,5732600.0,177.389999,178.289993,11772200.0,...,31491500.0,341.320007,329.420013,86215400.0,1.981,1.977,0.0,432.660004,421.950012,132578000.0
8100,2022-02-24,37.500000,30.320000,0,322.820007,332.339996,14167100.0,182.589996,177.139999,32726000.0,...,52221100.0,318.839996,340.489990,130614100.0,1.882,1.969,0.0,411.019989,428.299988,213942900.0
8101,2022-02-25,31.680000,27.590000,0,333.679993,340.540009,9489000.0,176.419998,176.550003,11526000.0,...,33631400.0,341.309998,345.769989,78776600.0,1.998,1.986,0.0,429.609985,437.750000,121804500.0

In [8]:
#### Clean Combined_Variables & Combined_SP500

In [9]:
Cleaned_Combined_Variables= Combined_Variables.dropna()
Cleaned_Combined_Variables

,Date,VIX_Open,VIX_Close,VIX_Volume,DOW_Open,DOW_Close,DOW_Volume,GLD_Open,GLD_Close,GLD_Volume,...,R2K_Volume,NASDAQ_Open,NASDAQ_Close,NASDAQ_Volume,10YR_Open,10YR_Close,10YR_Volume,SPY_Open,SPY_Close,SPY_Volume
3754,2004-11-18,13.220000,12.980000,0,105.919998,106.000000,4714100.0,44.430000,44.380001,5992000.0,...,12526000.0,38.980000,39.290001,94901100.0,4.144,4.117,0.0,118.529999,118.739998,31854300.0
3755,2004-11-19,12.790000,13.500000,0,105.660004,104.570000,6968500.0,44.490002,44.779999,11655300.0,...,11445000.0,39.240002,38.680000,118448900.0,4.117,4.196,0.0,118.699997,117.419998,54276500.0
3756,2004-11-22,13.710000,12.970000,0,104.370003,104.800003,8335900.0,44.750000,44.950001,11996000.0,...,13922200.0,38.610001,39.049999,79882600.0,4.188,4.165,0.0,117.169998,117.980003,37560200.0
3757,2004-11-23,12.780000,12.670000,0,104.830002,104.989998,7527500.0,44.880001,44.750000,3169200.0,...,21859400.0,39.009998,38.990002,91925300.0,4.199,4.184,0.0,117.930000,118.160004,41968800.0
3758,2004-11-24,12.580000,12.720000,0,105.019997,105.029999,6210400.0,44.930000,45.049999,6105100.0,...,11408600.0,39.090000,39.330002,74051700.0,4.178,4.195,0.0,118.269997,118.440002,29724800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8097,2022-02-18,26.660000,27.750000,0,342.899994,340.980011,6191000.0,177.070007,177.119995,12754400.0,...,36203900.0,346.410004,341.510010,79821000.0,1.960,1.932,0.0,437.329987,434.230011,132642900.0
8098,2022-02-22,31.799999,28.809999,0,338.790009,336.010010,7942700.0,177.669998,177.490005,14960500.0,...,31847100.0,338.489990,338.079987,85967100.0,1.944,1.948,0.0,431.890015,429.570007,124391800.0
8099,2022-02-23,28.040001,31.020000,0,338.160004,331.519989,5732600.0,177.389999,178.289993,11772200.0,...,31491500.0,341.320007,329.420013,86215400.0,1.981,1.977,0.0,432.660004,421.950012,132578000.0
8100,2022-02-24,37.500000,30.320000,0,322.820007,332.339996,14167100.0,182.589996,177.139999,32726000.0,...,52221100.0,318.839996,340.489990,130614100.0,1.882,1.969,0.0,411.019989,428.299988,213942900.0
8101,2022-02-25,31.680000,27.590000,0,333.679993,340.540009,9489000.0,176.419998,176.550003,11526000.0,...,33631400.0,341.309998,345.769989,78776600.0,1.998,1.986,0.0,429.609985,437.750000,121804500.0

In [10]:
Cleaned_SP500= Combined_SP500.dropna()
Cleaned_SP500

,Date,SPMAT_Open,SPMAT_Close,SPMAT_Volume,SPENERGY_Open,SPENERGY_Close,SPENERGY_Volume,SPFINANCE_Open,SPFINANCE_Close,SPFINANCE_Volume,...,SPStaples_Volume,SPUTIL_Open,SPUTIL_Close,SPUTIL_Volume,SPHealth_Open,SPHealth_Close,SPHealth_Volume,SPDisc_Open,SPDisc_Close,SPDisc_Volume
0,1998-12-22,20.781250,20.828125,1900,23.312500,23.265625,15200,19.052092,18.937855,55887,...,150300,30.250000,29.828125,7900,24.812500,25.031250,5700,25.312500,25.468750,3700
1,1998-12-23,20.968750,21.046875,700,23.343750,23.750000,67800,18.861698,19.217100,78784,...,44000,29.796875,29.703125,24100,25.187500,25.593750,18100,25.500000,25.578125,12000
2,1998-12-24,21.296875,21.531250,1500,23.812500,23.625000,12300,19.217100,19.344028,43824,...,45500,30.218750,30.250000,23800,25.625000,25.750000,4900,25.937500,26.046875,1600
3,1998-12-28,21.500000,21.343750,2500,23.750000,23.500000,13500,19.331335,19.090172,51948,...,25400,30.187500,30.093750,3100,25.671875,25.375000,15500,25.921875,25.812500,8600
4,1998-12-29,21.734375,21.734375,100,23.562500,23.734375,22000,19.115557,19.293259,100819,...,123500,30.218750,30.593750,12000,25.375000,25.937500,5300,25.890625,26.375000,1100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5828,2022-02-18,84.180000,83.860001,8964800,67.500000,68.050003,31630200,39.189999,39.220001,47813800,...,16469700,66.120003,66.220001,16843400,128.350006,127.510002,13505000,181.600006,180.000000,9495200
5829,2022-02-22,83.459999,82.669998,10654400,70.110001,66.949997,46501400,39.040001,39.020000,60719700,...,21545800,66.459999,66.150002,17210700,127.059998,127.190002,13682100,177.479996,174.750000,13672800
5830,2022-02-23,83.199997,81.610001,9581100,67.339996,67.639999,33979000,39.310001,38.340000,64169800,...,15134300,66.269997,65.029999,17291800,127.839996,126.550003,12022800,176.119995,168.910004,13567200
5831,2022-02-24,79.769997,81.370003,15903500,69.080002,67.110001,61742900,37.070000,37.880001,143075700,...,30125500,64.610001,65.550003,28660000,124.290001,127.059998,23220000,161.970001,172.770004,20868000
5832,2022-02-25,81.739998,84.339996,11129200,67.260002,68.879997,39203200,38.130001,39.099998,99105200,...,21138400,66.129997,67.580002,21264000,127.629997,130.949997,17010500,173.289993,176.190002,13669000

In [11]:
for column in Cleaned_SP500.columns:
    print(f"Column {column} has {Cleaned_SP500[column].isnull().sum()} null values")

Column Date has 0 null values
Column SPMAT_Open has 0 null values
Column SPMAT_Close has 0 null values
Column SPMAT_Volume has 0 null values
Column SPENERGY_Open has 0 null values
Column SPENERGY_Close has 0 null values
Column SPENERGY_Volume has 0 null values
Column SPFINANCE_Open has 0 null values
Column SPFINANCE_Close has 0 null values
Column SPFINANCE_Volume has 0 null values
Column SPINDUS_Open has 0 null values
Column SPINDUS_Close has 0 null values
Column SPINDUS_Volume has 0 null values
Column SPTech_Open has 0 null values
Column SPTech_Close has 0 null values
Column SPTech_Volume has 0 null values
Column SPStaples_Open has 0 null values
Column SPStaples_Close has 0 null values
Column SPStaples_Volume has 0 null values
Column SPUTIL_Open has 0 null values
Column SPUTIL_Close has 0 null values
Column SPUTIL_Volume has 0 null values
Column SPHealth_Open has 0 null values
Column SPHealth_Close has 0 null values
Column SPHealth_Volume has 0 null values
Column SPDisc_Open has 0 null values
Column SPDisc_Close has 0 null values
Column SPDisc_Volume has 0 null values

In [12]:
for column in Cleaned_Combined_Variables.columns:
    print(f"Column {column} has {Cleaned_Combined_Variables[column].isnull().sum()} null values")

Column Date has 0 null values
Column VIX_Open has 0 null values
Column VIX_Close has 0 null values
Column VIX_Volume has 0 null values
Column DOW_Open has 0 null values
Column DOW_Close has 0 null values
Column DOW_Volume has 0 null values
Column GLD_Open has 0 null values
Column GLD_Close has 0 null values
Column GLD_Volume has 0 null values
Column R2K_Open has 0 null values
Column R2K_Close has 0 null values
Column R2K_Volume has 0 null values
Column NASDAQ_Open has 0 null values
Column NASDAQ_Close has 0 null values
Column NASDAQ_Volume has 0 null values
Column 10YR_Open has 0 null values
Column 10YR_Close has 0 null values
Column 10YR_Volume has 0 null values
Column SPY_Open has 0 null values
Column SPY_Close has 0 null values
Column SPY_Volume has 0 null values

In [13]:
Cleaned_SP500.head()

,Date,SPMAT_Open,SPMAT_Close,SPMAT_Volume,SPENERGY_Open,SPENERGY_Close,SPENERGY_Volume,SPFINANCE_Open,SPFINANCE_Close,SPFINANCE_Volume,...,SPStaples_Volume,SPUTIL_Open,SPUTIL_Close,SPUTIL_Volume,SPHealth_Open,SPHealth_Close,SPHealth_Volume,SPDisc_Open,SPDisc_Close,SPDisc_Volume
0,1998-12-22,20.781250,20.828125,1900,23.31250,23.265625,15200,19.052092,18.937855,55887,...,150300,30.250000,29.828125,7900,24.812500,25.03125,5700,25.312500,25.468750,3700
1,1998-12-23,20.968750,21.046875,700,23.34375,23.750000,67800,18.861698,19.217100,78784,...,44000,29.796875,29.703125,24100,25.187500,25.59375,18100,25.500000,25.578125,12000
2,1998-12-24,21.296875,21.531250,1500,23.81250,23.625000,12300,19.217100,19.344028,43824,...,45500,30.218750,30.250000,23800,25.625000,25.75000,4900,25.937500,26.046875,1600
3,1998-12-28,21.500000,21.343750,2500,23.75000,23.500000,13500,19.331335,19.090172,51948,...,25400,30.187500,30.093750,3100,25.671875,25.37500,15500,25.921875,25.812500,8600
4,1998-12-29,21.734375,21.734375,100,23.56250,23.734375,22000,19.115557,19.293259,100819,...,123500,30.218750,30.593750,12000,25.375000,25.93750,5300,25.890625,26.375000,1100

In [15]:
Cleaned_Combined_Variables.head()

,Date,VIX_Open,VIX_Close,VIX_Volume,DOW_Open,DOW_Close,DOW_Volume,GLD_Open,GLD_Close,GLD_Volume,...,R2K_Volume,NASDAQ_Open,NASDAQ_Close,NASDAQ_Volume,10YR_Open,10YR_Close,10YR_Volume,SPY_Open,SPY_Close,SPY_Volume
3754,2004-11-18,13.22,12.98,0,105.919998,106.000000,4714100.0,44.430000,44.380001,5992000.0,...,12526000.0,38.980000,39.290001,94901100.0,4.144,4.117,0.0,118.529999,118.739998,31854300.0
3755,2004-11-19,12.79,13.50,0,105.660004,104.570000,6968500.0,44.490002,44.779999,11655300.0,...,11445000.0,39.240002,38.680000,118448900.0,4.117,4.196,0.0,118.699997,117.419998,54276500.0
3756,2004-11-22,13.71,12.97,0,104.370003,104.800003,8335900.0,44.750000,44.950001,11996000.0,...,13922200.0,38.610001,39.049999,79882600.0,4.188,4.165,0.0,117.169998,117.980003,37560200.0
3757,2004-11-23,12.78,12.67,0,104.830002,104.989998,7527500.0,44.880001,44.750000,3169200.0,...,21859400.0,39.009998,38.990002,91925300.0,4.199,4.184,0.0,117.930000,118.160004,41968800.0
3758,2004-11-24,12.58,12.72,0,105.019997,105.029999,6210400.0,44.930000,45.049999,6105100.0,...,11408600.0,39.090000,39.330002,74051700.0,4.178,4.195,0.0,118.269997,118.440002,29724800.0

In [16]:
merged_data = pd.merge(Cleaned_SP500, Cleaned_Combined_Variables, how='outer', on='Date' )

In [18]:
cleaned_final = merged_data.dropna()

In [22]:
cleaned_final

,Date,SPMAT_Open,SPMAT_Close,SPMAT_Volume,SPENERGY_Open,SPENERGY_Close,SPENERGY_Volume,SPFINANCE_Open,SPFINANCE_Close,SPFINANCE_Volume,...,R2K_Volume,NASDAQ_Open,NASDAQ_Close,NASDAQ_Volume,10YR_Open,10YR_Close,10YR_Volume,SPY_Open,SPY_Close,SPY_Volume
1485,2004-11-18,29.049999,29.139999,552700,35.790001,35.950001,2195000,24.207960,24.102356,2839178,...,12526000.0,38.980000,39.290001,94901100.0,4.144,4.117,0.0,118.529999,118.739998,31854300.0
1486,2004-11-19,29.000000,28.940001,283800,36.150002,36.380001,3936400,24.224209,23.793665,11335540,...,11445000.0,39.240002,38.680000,118448900.0,4.117,4.196,0.0,118.699997,117.419998,54276500.0
1487,2004-11-22,28.889999,29.280001,664300,36.430000,36.959999,3719800,23.679935,23.931763,1874074,...,13922200.0,38.610001,39.049999,79882600.0,4.188,4.165,0.0,117.169998,117.980003,37560200.0
1488,2004-11-23,29.360001,29.139999,316000,37.000000,37.189999,1845900,23.883022,23.988626,1855117,...,21859400.0,39.009998,38.990002,91925300.0,4.199,4.184,0.0,117.930000,118.160004,41968800.0
1489,2004-11-24,29.150000,29.420000,690300,37.299999,37.500000,3549200,24.159220,24.086109,2208537,...,11408600.0,39.090000,39.330002,74051700.0,4.178,4.195,0.0,118.269997,118.440002,29724800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5828,2022-02-18,84.180000,83.860001,8964800,67.500000,68.050003,31630200,39.189999,39.220001,47813800,...,36203900.0,346.410004,341.510010,79821000.0,1.960,1.932,0.0,437.329987,434.230011,132642900.0
5829,2022-02-22,83.459999,82.669998,10654400,70.110001,66.949997,46501400,39.040001,39.020000,60719700,...,31847100.0,338.489990,338.079987,85967100.0,1.944,1.948,0.0,431.890015,429.570007,124391800.0
5830,2022-02-23,83.199997,81.610001,9581100,67.339996,67.639999,33979000,39.310001,38.340000,64169800,...,31491500.0,341.320007,329.420013,86215400.0,1.981,1.977,0.0,432.660004,421.950012,132578000.0
5831,2022-02-24,79.769997,81.370003,15903500,69.080002,67.110001,61742900,37.070000,37.880001,143075700,...,52221100.0,318.839996,340.489990,130614100.0,1.882,1.969,0.0,411.019989,428.299988,213942900.0
5832,2022-02-25,81.739998,84.339996,11129200,67.260002,68.879997,39203200,38.130001,39.099998,99105200,...,33631400.0,341.309998,345.769989,78776600.0,1.998,1.986,0.0,429.609985,437.750000,121804500.0

In [24]:
cleaned_final['Date'] = pd.to_datetime(cleaned_final['Date'])
cleaned_final

/var/folders/n9/t7mhzk117rq2k3zg04nn_fmc0000gn/T/ipykernel_93329/3372200776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_final['Date'] = pd.to_datetime(cleaned_final['Date'])

,Date,SPMAT_Open,SPMAT_Close,SPMAT_Volume,SPENERGY_Open,SPENERGY_Close,SPENERGY_Volume,SPFINANCE_Open,SPFINANCE_Close,SPFINANCE_Volume,...,R2K_Volume,NASDAQ_Open,NASDAQ_Close,NASDAQ_Volume,10YR_Open,10YR_Close,10YR_Volume,SPY_Open,SPY_Close,SPY_Volume
1485,2004-11-18,29.049999,29.139999,552700,35.790001,35.950001,2195000,24.207960,24.102356,2839178,...,12526000.0,38.980000,39.290001,94901100.0,4.144,4.117,0.0,118.529999,118.739998,31854300.0
1486,2004-11-19,29.000000,28.940001,283800,36.150002,36.380001,3936400,24.224209,23.793665,11335540,...,11445000.0,39.240002,38.680000,118448900.0,4.117,4.196,0.0,118.699997,117.419998,54276500.0
1487,2004-11-22,28.889999,29.280001,664300,36.430000,36.959999,3719800,23.679935,23.931763,1874074,...,13922200.0,38.610001,39.049999,79882600.0,4.188,4.165,0.0,117.169998,117.980003,37560200.0
1488,2004-11-23,29.360001,29.139999,316000,37.000000,37.189999,1845900,23.883022,23.988626,1855117,...,21859400.0,39.009998,38.990002,91925300.0,4.199,4.184,0.0,117.930000,118.160004,41968800.0
1489,2004-11-24,29.150000,29.420000,690300,37.299999,37.500000,3549200,24.159220,24.086109,2208537,...,11408600.0,39.090000,39.330002,74051700.0,4.178,4.195,0.0,118.269997,118.440002,29724800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5828,2022-02-18,84.180000,83.860001,8964800,67.500000,68.050003,31630200,39.189999,39.220001,47813800,...,36203900.0,346.410004,341.510010,79821000.0,1.960,1.932,0.0,437.329987,434.230011,132642900.0
5829,2022-02-22,83.459999,82.669998,10654400,70.110001,66.949997,46501400,39.040001,39.020000,60719700,...,31847100.0,338.489990,338.079987,85967100.0,1.944,1.948,0.0,431.890015,429.570007,124391800.0
5830,2022-02-23,83.199997,81.610001,9581100,67.339996,67.639999,33979000,39.310001,38.340000,64169800,...,31491500.0,341.320007,329.420013,86215400.0,1.981,1.977,0.0,432.660004,421.950012,132578000.0
5831,2022-02-24,79.769997,81.370003,15903500,69.080002,67.110001,61742900,37.070000,37.880001,143075700,...,52221100.0,318.839996,340.489990,130614100.0,1.882,1.969,0.0,411.019989,428.299988,213942900.0
5832,2022-02-25,81.739998,84.339996,11129200,67.260002,68.879997,39203200,38.130001,39.099998,99105200,...,33631400.0,341.309998,345.769989,78776600.0,1.998,1.986,0.0,429.609985,437.750000,121804500.0

In [25]:
cleaned_final.dtypes

Date                datetime64[ns]
SPMAT_Open                 float64
SPMAT_Close                float64
SPMAT_Volume                 int64
SPENERGY_Open              float64
SPENERGY_Close             float64
SPENERGY_Volume              int64
SPFINANCE_Open             float64
SPFINANCE_Close            float64
SPFINANCE_Volume             int64
SPINDUS_Open               float64
SPINDUS_Close              float64
SPINDUS_Volume               int64
SPTech_Open                float64
SPTech_Close               float64
SPTech_Volume                int64
SPStaples_Open             float64
SPStaples_Close            float64
SPStaples_Volume             int64
SPUTIL_Open                float64
SPUTIL_Close               float64
SPUTIL_Volume                int64
SPHealth_Open              float64
SPHealth_Close             float64
SPHealth_Volume              int64
SPDisc_Open                float64
SPDisc_Close               float64
SPDisc_Volume                int64
VIX_Open                   float64
VIX_Close                  float64
VIX_Volume                 float64
DOW_Open                   float64
DOW_Close                  float64
DOW_Volume                 float64
GLD_Open                   float64
GLD_Close                  float64
GLD_Volume                 float64
R2K_Open                   float64
R2K_Close                  float64
R2K_Volume                 float64
NASDAQ_Open                float64
NASDAQ_Close               float64
NASDAQ_Volume              float64
10YR_Open                  float64
10YR_Close                 float64
10YR_Volume                float64
SPY_Open                   float64
SPY_Close                  float64
SPY_Volume                 float64
dtype: object

In [26]:
cleaned_final.head()

,Date,SPMAT_Open,SPMAT_Close,SPMAT_Volume,SPENERGY_Open,SPENERGY_Close,SPENERGY_Volume,SPFINANCE_Open,SPFINANCE_Close,SPFINANCE_Volume,...,R2K_Volume,NASDAQ_Open,NASDAQ_Close,NASDAQ_Volume,10YR_Open,10YR_Close,10YR_Volume,SPY_Open,SPY_Close,SPY_Volume
1485,2004-11-18,29.049999,29.139999,552700,35.790001,35.950001,2195000,24.207960,24.102356,2839178,...,12526000.0,38.980000,39.290001,94901100.0,4.144,4.117,0.0,118.529999,118.739998,31854300.0
1486,2004-11-19,29.000000,28.940001,283800,36.150002,36.380001,3936400,24.224209,23.793665,11335540,...,11445000.0,39.240002,38.680000,118448900.0,4.117,4.196,0.0,118.699997,117.419998,54276500.0
1487,2004-11-22,28.889999,29.280001,664300,36.430000,36.959999,3719800,23.679935,23.931763,1874074,...,13922200.0,38.610001,39.049999,79882600.0,4.188,4.165,0.0,117.169998,117.980003,37560200.0
1488,2004-11-23,29.360001,29.139999,316000,37.000000,37.189999,1845900,23.883022,23.988626,1855117,...,21859400.0,39.009998,38.990002,91925300.0,4.199,4.184,0.0,117.930000,118.160004,41968800.0
1489,2004-11-24,29.150000,29.420000,690300,37.299999,37.500000,3549200,24.159220,24.086109,2208537,...,11408600.0,39.090000,39.330002,74051700.0,4.178,4.195,0.0,118.269997,118.440002,29724800.0

In [ ]:
## Model for getting